### ISSUE TITLE
Logo design for HuskyRobotController1

### ISSUE THREAD

**Issue by zuurw** [eduardorasgado/HuskyRobotController1#1]
Hi @eduardorasgado, do you need a logo for this project too? It will be a pleasure for me to work again with you. If it's something you're interested in, please, let me know!
Best Regards
Zuur

**Comment by eduardorasgado** [comment]
Yeep! You're welcome @zuurw . IN this project we control a husky robot using odometry and mapping with laser scans. The logo design could be a little bit tricky because we dont want to tell the people we are doing laser scanning, we want to deliver a solution for their robots as a different concept, so: why don't we try to create a Husky dog face logo instead of taking inpiration from robotics concepts. :100:

**Comment by zuurw** [comment]
Hello @eduardorasgado, as you requested here is my design for this project, it´s a Husky face :)
I think the logo it´s modern and friendly too, it looks good in black and white versions and also in small sizes.

I put 3 typeface for you to choose.

Send me your feedback

![proposal](https://user-images.githubusercontent.com/40801473/43835586-68ee321e-9b0a-11e8-944b-c9339c2838bb.png)

**Comment by zuurw** [comment]
Hi @eduardorasgado , did you see my logo design for this project?

Best Regards!

**Comment by eduardorasgado** [comment]
I have seen it right now, it's cool bro! I like the one in the middle. I think the topography combined with the logo. Send me the pull request @zuurw : 💯 and sorry for the delay.

**Comment by zuurw** [comment]
I submited the PR.

Best Regards
